যখন আমি “https://firebase.studio/” এই পেইজে থাকি তখন আমার কুকি হচ্ছে “[
    {
        "domain": ".firebase.studio",
        "expirationDate": 1783427612.347821,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.1.1985854349.1748709204",
        "id": 1
    },
    {
        "domain": ".firebase.studio",
        "expirationDate": 1783427612.346549,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_CW55HF8NVT",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS2.1.s1748867366$o5$g0$t1748867612$j60$l0$h0",
        "id": 2
    }
]
” আবার যখন আমি “https://studio.firebase.google.com/?utm_source=firebase_studio_marketing&utm_medium=et&utm_campaign=FY25-Q2-firebasestudio_nextlaunch&utm_content=hero_tryfirebasestudio&utm_term=-&pli=1”এই পেইজে যাই তখন  আমার কুকি হচ্ছে “[
    {
        "domain": ".google.com",
        "expirationDate": 1783427802.425556,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "lTkuQI6N_xrqXggp/ASK_oMgaLaNB6GUw5",
        "id": 1
    },
    {
        "domain": ".google.com",
        "expirationDate": 1783427802.425521,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a000xghBy-5PqOPR30G5Bp3_q7zOPVJxlBDvXp2NwSkhBmDVx7zn1vUUaSrLB7vRSL2yj3zHmQACgYKARISARUSFQHGX2Mi7RIsjKswdZWaUxhWhqTkuRoVAUF8yKqrwrYlhNsb75ZDB0Fhcb2a0076",
        "id": 2
    },
    {
        "domain": ".google.com",
        "expirationDate": 1783427802.425559,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "lTkuQI6N_xrqXggp/ASK_oMgaLaNB6GUw5",
        "id": 3
    },
    {
        "domain": ".google.com",
        "expirationDate": 1783427802.425525,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a000xghBy-5PqOPR30G5Bp3_q7zOPVJxlBDvXp2NwSkhBmDVx7znZ7BExwWZx7EBSpD-99WWFAACgYKAUASARUSFQHGX2MiVWkdnE81lnkFcGhcZ23jGRoVAUF8yKq0fwXUIY2Cq3e_H8elsD8v0076",
        "id": 4
    },
    {
        "domain": ".google.com",
        "expirationDate": 1783427802.42555,
        "hostOnly": false,
        "httpOnly": false,
        "name": "APISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "5cGDUDkcNshMet9Z/AKH3AmIliIQEVfByh",
        "id": 5
    },
    {
        "domain": ".google.com",
        "expirationDate": 1783427802.425546,
        "hostOnly": false,
        "httpOnly": true,
        "name": "HSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "APIoDbdibnwu3z5LU",
        "id": 6
    },
    {
        "domain": ".google.com",
        "expirationDate": 1783427802.425553,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "lTkuQI6N_xrqXggp/ASK_oMgaLaNB6GUw5",
        "id": 7
    },
    {
        "domain": ".google.com",
        "expirationDate": 1783427802.425517,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "g.a000xghBy-5PqOPR30G5Bp3_q7zOPVJxlBDvXp2NwSkhBmDVx7znfaay2vdfUQyDJ746PSrgvAACgYKAY0SARUSFQHGX2MijSNxJ4znyC0Vqni5Y_mr9xoVAUF8yKoQGOiZtf08MGTMyn5IHVLv0076",
        "id": 8
    },
    {
        "domain": ".google.com",
        "expirationDate": 1783427802.425548,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AcKBTqprXTDAEkZ2r",
        "id": 9
    }
]
” আবার যখন প্রজেক্ট এর উপর অর্থাৎ class="main-target" এই নামের বাটন এর উপর ক্লিক করি তখন আমার কুকি হচ্ছে name: WorkstationJwtPartitioned   value: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2Nsb3VkLmdvb2dsZS5jb20vd29ya3N0YXRpb25zIiwiYXVkIjoiZmlyZWJhc2Utc2Vjb25kLTE3NDg3MjAyNjAyNDIuY2x1c3Rlci1lamQyMmtxbnk1aHR1djVkZm93b3lpcHQ1Mi5jbG91ZHdvcmtzdGF0aW9ucy5kZXYiLCJpYXQiOjE3NDg4NDIxMTYsImV4cCI6MTc0ODkyODUxNn0.JRuXciKCv63b8Jm_XTmhqhkLN_JCVw1pIEoLdn81tXiGTU6Tld_XoTrC4OkB7KMl_rX3IoevRy9A1TB2Xsrf-yTbK9AACzibBhprfjjkTLFMJlEd4sCjA_mPAFYVvxfpkL0G3mgW5jcOriMor89w_yqTcV7L7BQY7WeWjdhnNcc5Ys2Kzv4UKOcHURLW_UIPky9j6QJ9FGqGNEyq9u3jbeCtL0O29Yn2r1yZoP8ha_L2bejhj5aFuRjO96jVFtooB0P5F3-_9blZG5wXiy7T4SE73io7JFQ_YTO8Lv9lOVfgnMNQEu9hbgRksY1UA3yPaaFwh09_pj4B-H6SIDT-WA   এই সব কিছু বিবেচনা করে এখন তুমি আমার সকল সমস্যার সমাধান করে দাও
